name: 'Ramsey GIFifier'
description: 'Posts a Ramsey gif on every PR as a reward for pushing code.'
author: 'Ruairidh Wynne-McHardy and Ethan Dowler'
branding:
  icon: 'code'  
  color: 'blue'
inputs:
  GITHUB_TOKEN:        #Github token      
    description: 'Github token for the repository.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
